# Generated by Django 3.1.13 on 2021-07-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rate', '0003_movie_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
