# Generated by Django 3.1.13 on 2021-07-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210710_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='core.Tag'),
        ),
    ]
