# Generated by Django 3.1.13 on 2021-07-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210711_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='core.Tag'),
        ),
    ]
