# Generated by Django 3.1.13 on 2021-10-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211003_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='bio',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_place',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to='images/directors'),
        ),
    ]
