version:  "3.8"
services: 
    api: 
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./api:/api
        command: >
            sh -c "
            python3 manage.py wait_for_db &&
            python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000
            "
        environment:
            - DB_HOST=db
            - DB_NAME=soul_rate
            - DB_USER=user
            - DB_PASS=pass
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_DB=soul_rate
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass